# Generated by Django 4.2.7 on 2025-10-14 04:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Traveller",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("employee_id", models.CharField(blank=True, max_length=100)),
                ("department", models.CharField(blank=True, max_length=100)),
                ("cost_center", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travellers",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "travellers",
                "indexes": [
                    models.Index(
                        fields=["organization", "last_name", "first_name"],
                        name="travellers_organiz_df7b3e_idx",
                    ),
                    models.Index(
                        fields=["organization", "is_active"],
                        name="travellers_organiz_7973d2_idx",
                    ),
                ],
                "unique_together": {("organization", "employee_id")},
            },
        ),
    ]
