# Generated by Django 4.2.7 on 2025-10-14 05:06

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0001_initial"),
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("booking_reference", models.CharField(max_length=100)),
                (
                    "booking_type",
                    models.CharField(
                        choices=[
                            ("AIR", "Air Travel"),
                            ("HOTEL", "Accommodation"),
                            ("CAR", "Car Hire"),
                            ("OTHER", "Other Services"),
                        ],
                        max_length=20,
                    ),
                ),
                ("booking_date", models.DateField()),
                ("travel_date", models.DateField()),
                ("return_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CONFIRMED", "Confirmed"),
                            ("CANCELLED", "Cancelled"),
                            ("REFUNDED", "Refunded"),
                            ("PENDING", "Pending"),
                        ],
                        default="CONFIRMED",
                        max_length=20,
                    ),
                ),
                ("currency", models.CharField(default="AUD", max_length=3)),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "base_fare",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "taxes",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "fees",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="organizations.organization",
                    ),
                ),
                (
                    "traveller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="bookings.traveller",
                    ),
                ),
            ],
            options={
                "db_table": "bookings",
                "indexes": [
                    models.Index(
                        fields=["organization", "booking_date"],
                        name="bookings_organiz_a7488f_idx",
                    ),
                    models.Index(
                        fields=["organization", "travel_date"],
                        name="bookings_organiz_46a7d8_idx",
                    ),
                    models.Index(
                        fields=["traveller", "travel_date"],
                        name="bookings_travell_0bb930_idx",
                    ),
                    models.Index(
                        fields=["booking_reference"], name="bookings_booking_4d53ac_idx"
                    ),
                    models.Index(
                        fields=["booking_type", "status"],
                        name="bookings_booking_a1dcd6_idx",
                    ),
                ],
            },
        ),
    ]
