# Generated by Django 4.2.7 on 2025-10-15 00:04

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("imports", "0001_initial"),
        ("organizations", "0001_initial"),
        ("bookings", "0002_booking"),
    ]

    operations = [
        migrations.CreateModel(
            name="AirBooking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "trip_type",
                    models.CharField(
                        choices=[
                            ("ONE_WAY", "One Way"),
                            ("RETURN", "Return"),
                            ("MULTI_CITY", "Multi-City"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "travel_class",
                    models.CharField(
                        choices=[
                            ("FIRST", "First Class"),
                            ("BUSINESS", "Business Class"),
                            ("PREMIUM_ECONOMY", "Premium Economy"),
                            ("ECONOMY", "Economy"),
                            ("RESTRICTED_ECONOMY", "Restricted Economy"),
                        ],
                        max_length=30,
                    ),
                ),
                ("ticket_number", models.CharField(blank=True, max_length=50)),
                (
                    "primary_airline_iata_code",
                    models.CharField(blank=True, max_length=3),
                ),
                ("primary_airline_name", models.CharField(blank=True, max_length=100)),
                ("origin_airport_iata_code", models.CharField(max_length=3)),
                ("destination_airport_iata_code", models.CharField(max_length=3)),
                (
                    "lowest_fare_available",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("lowest_fare_currency", models.CharField(blank=True, max_length=3)),
                (
                    "potential_savings",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="air_details",
                        to="bookings.booking",
                    ),
                ),
            ],
            options={
                "db_table": "air_bookings",
            },
        ),
        migrations.CreateModel(
            name="AccommodationBooking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("hotel_name", models.CharField(max_length=200)),
                ("hotel_chain", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("address", models.TextField(blank=True)),
                ("check_in_date", models.DateField()),
                ("check_out_date", models.DateField()),
                ("number_of_nights", models.IntegerField()),
                ("room_type", models.CharField(blank=True, max_length=100)),
                ("nightly_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="AUD", max_length=3)),
                (
                    "nightly_rate_base",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "total_amount_base",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accommodation_details",
                        to="bookings.booking",
                    ),
                ),
            ],
            options={
                "db_table": "accommodation_bookings",
            },
        ),
        migrations.CreateModel(
            name="ServiceFee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "fee_type",
                    models.CharField(
                        choices=[
                            ("BOOKING_ONLINE_DOM", "Online Booking - Domestic"),
                            ("BOOKING_ONLINE_INTL", "Online Booking - International"),
                            ("BOOKING_OFFLINE_DOM", "Offline Booking - Domestic"),
                            ("BOOKING_OFFLINE_INTL", "Offline Booking - International"),
                            ("CHANGE_FEE", "Change Fee"),
                            ("REFUND_FEE", "Refund Fee"),
                            ("AFTER_HOURS", "After Hours Fee"),
                            ("CONSULTATION", "Consultation Fee"),
                            ("OTHER", "Other Fee"),
                        ],
                        max_length=50,
                    ),
                ),
                ("fee_date", models.DateField()),
                ("currency", models.CharField(default="AUD", max_length=3)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "gst_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "amount_base",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "gst_amount_base",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=12, null=True
                    ),
                ),
                ("exchange_rate_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_fees",
                        to="bookings.booking",
                    ),
                ),
                (
                    "import_batch",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_fees",
                        to="imports.importbatch",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_fees",
                        to="organizations.organization",
                    ),
                ),
                (
                    "traveller",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_fees",
                        to="bookings.traveller",
                    ),
                ),
            ],
            options={
                "db_table": "service_fees",
                "indexes": [
                    models.Index(
                        fields=["organization", "fee_date"],
                        name="service_fee_organiz_850524_idx",
                    ),
                    models.Index(
                        fields=["fee_type", "fee_date"],
                        name="service_fee_fee_typ_bf9f5a_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("invoice_number", models.CharField(max_length=100)),
                ("invoice_date", models.DateField()),
                ("currency", models.CharField(default="AUD", max_length=3)),
                (
                    "invoice_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "gst_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "invoice_amount_base",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "gst_amount_base",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=12, null=True
                    ),
                ),
                ("exchange_rate_date", models.DateField(blank=True, null=True)),
                ("payment_status", models.CharField(default="UNPAID", max_length=20)),
                ("payment_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="bookings.booking",
                    ),
                ),
                (
                    "import_batch",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="imports.importbatch",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "invoices",
                "indexes": [
                    models.Index(
                        fields=["organization", "invoice_date"],
                        name="invoices_organiz_382970_idx",
                    ),
                    models.Index(
                        fields=["invoice_number"], name="invoices_invoice_7778bc_idx"
                    ),
                    models.Index(
                        fields=["booking"], name="invoices_booking_1788cc_idx"
                    ),
                ],
                "unique_together": {("organization", "invoice_number")},
            },
        ),
        migrations.CreateModel(
            name="CarHireBooking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rental_company", models.CharField(max_length=100)),
                ("vehicle_type", models.CharField(blank=True, max_length=100)),
                ("vehicle_class", models.CharField(blank=True, max_length=50)),
                ("pickup_location", models.CharField(max_length=200)),
                ("dropoff_location", models.CharField(max_length=200)),
                ("pickup_city", models.CharField(max_length=100)),
                ("pickup_date", models.DateField()),
                ("pickup_time", models.TimeField()),
                ("dropoff_date", models.DateField()),
                ("dropoff_time", models.TimeField()),
                ("number_of_days", models.IntegerField()),
                ("daily_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="AUD", max_length=3)),
                (
                    "daily_rate_base",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "total_amount_base",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="car_hire_details",
                        to="bookings.booking",
                    ),
                ),
            ],
            options={
                "db_table": "car_hire_bookings",
                "indexes": [
                    models.Index(
                        fields=["pickup_city", "pickup_date"],
                        name="car_hire_bo_pickup__d50437_idx",
                    ),
                    models.Index(
                        fields=["rental_company"], name="car_hire_bo_rental__add2a9_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AirSegment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("segment_number", models.IntegerField()),
                ("airline_iata_code", models.CharField(max_length=3)),
                ("airline_name", models.CharField(max_length=100)),
                ("flight_number", models.CharField(max_length=10)),
                ("origin_airport_iata_code", models.CharField(max_length=3)),
                ("destination_airport_iata_code", models.CharField(max_length=3)),
                ("departure_date", models.DateField()),
                ("departure_time", models.TimeField()),
                ("arrival_date", models.DateField()),
                ("arrival_time", models.TimeField()),
                ("booking_class", models.CharField(max_length=10)),
                ("fare_basis", models.CharField(blank=True, max_length=20)),
                ("distance_km", models.IntegerField(blank=True, null=True)),
                (
                    "air_booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="bookings.airbooking",
                    ),
                ),
            ],
            options={
                "db_table": "air_segments",
                "ordering": ["segment_number"],
                "indexes": [
                    models.Index(
                        fields=["air_booking", "segment_number"],
                        name="air_segment_air_boo_48d09e_idx",
                    ),
                    models.Index(
                        fields=[
                            "origin_airport_iata_code",
                            "destination_airport_iata_code",
                        ],
                        name="air_segment_origin__bfcf6c_idx",
                    ),
                    models.Index(
                        fields=["departure_date"], name="air_segment_departu_61ad09_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="airbooking",
            index=models.Index(
                fields=["origin_airport_iata_code", "destination_airport_iata_code"],
                name="air_booking_origin__c5dca4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="airbooking",
            index=models.Index(
                fields=["primary_airline_iata_code"],
                name="air_booking_primary_d16fc9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="accommodationbooking",
            index=models.Index(
                fields=["city", "check_in_date"], name="accommodati_city_2c7cab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="accommodationbooking",
            index=models.Index(
                fields=["hotel_chain"], name="accommodati_hotel_c_74f9c9_idx"
            ),
        ),
    ]
