# Generated by Django 4.2.7 on 2025-10-15 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("reference_data", "0002_carrentalcompany_hotelchain"),
        (
            "bookings",
            "0003_airbooking_accommodationbooking_servicefee_invoice_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="accommodationbooking",
            name="hotel_chain_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="reference_data.hotelchain",
                verbose_name="Hotel Chain Reference",
            ),
        ),
        migrations.AddField(
            model_name="carhirebooking",
            name="rental_company_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="reference_data.carrentalcompany",
                verbose_name="Rental Company Reference",
            ),
        ),
        migrations.AddIndex(
            model_name="accommodationbooking",
            index=models.Index(
                fields=["hotel_chain_ref"], name="accommodati_hotel_c_8f1406_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carhirebooking",
            index=models.Index(
                fields=["rental_company_ref"], name="car_hire_bo_rental__bba20c_idx"
            ),
        ),
    ]
