# Generated by Django 4.2.7 on 2025-10-16 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bookings", "0004_accommodationbooking_hotel_chain_ref_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="accommodationbooking",
            name="accommodati_hotel_c_8f1406_idx",
        ),
        migrations.RemoveIndex(
            model_name="booking",
            name="bookings_booking_4d53ac_idx",
        ),
        migrations.RemoveIndex(
            model_name="carhirebooking",
            name="car_hire_bo_rental__bba20c_idx",
        ),
        migrations.RemoveField(
            model_name="accommodationbooking",
            name="hotel_chain_ref",
        ),
        migrations.RemoveField(
            model_name="carhirebooking",
            name="rental_company_ref",
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='booking_reference',
            new_name='agent_booking_reference',
        ),
        migrations.AddField(
            model_name="booking",
            name="supplier_reference",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Supplier Reference"
            ),
        ),
        migrations.AddField(
            model_name="traveller",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="Link this traveller to a user account if they need platform access",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="traveller_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User Account",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["agent_booking_reference"], name="bookings_agent_b_47b787_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["supplier_reference"], name="bookings_supplie_d17601_idx"
            ),
        ),
    ]
