# Generated by Django 4.2.7 on 2025-10-16 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "bookings",
            "0005_remove_accommodationbooking_accommodati_hotel_c_8f1406_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="travel_arranger",
            field=models.ForeignKey(
                blank=True,
                help_text="Person within the organization who arranged this booking",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings_arranged",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Travel Arranger",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="travel_consultant",
            field=models.ForeignKey(
                blank=True,
                help_text="Travel agent staff member who processed this booking",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings_consulted",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Travel Agent Consultant",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="agent_booking_reference",
            field=models.CharField(
                max_length=100, verbose_name="Agent Booking Reference"
            ),
        ),
    ]
