# Generated by Django 4.2.7 on 2025-10-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0006_booking_travel_arranger_booking_travel_consultant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="travel_arranger_text",
            field=models.CharField(
                blank=True,
                help_text="Fallback when arranger cannot be matched to a user account",
                max_length=200,
                verbose_name="Travel Arranger (Text)",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="travel_consultant_text",
            field=models.CharField(
                blank=True,
                help_text="Fallback when consultant cannot be matched to a user account",
                max_length=200,
                verbose_name="Travel Consultant (Text)",
            ),
        ),
    ]
