# Generated by Django 5.2.7 on 2025-10-16 22:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0007_booking_travel_arranger_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="airsegment",
            name="carbon_emissions_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="CO2 emissions in kilograms for this segment (ICAO standards)",
                max_digits=8,
                null=True,
            ),
        ),
    ]
