# Generated by Django 5.2.7 on 2025-10-17 01:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0008_rename_iata_fields_and_add_carbon"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="base_fare_base",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="exchange_rate",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="exchange_rate_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="fees_base",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="taxes_base",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="total_amount_base",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
