# Generated by Django 5.2.7 on 2025-10-27 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0009_booking_base_fare_base_booking_exchange_rate_and_more"),
        ("imports", "0001_initial"),
        ("organizations", "0002_organization_ap_contact_email_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="booking",
            name="bookings_booking_a1dcd6_idx",
        ),
        migrations.RemoveIndex(
            model_name="booking",
            name="bookings_supplie_d17601_idx",
        ),
        migrations.RemoveIndex(
            model_name="servicefee",
            name="service_fee_fee_typ_bf9f5a_idx",
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="invoice_amount",
            new_name="total_amount",
        ),
        migrations.RenameField(
            model_name="servicefee",
            old_name="amount",
            new_name="fee_amount",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="booking_type",
        ),
        migrations.RemoveField(
            model_name="carhirebooking",
            name="vehicle_class",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="exchange_rate",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="exchange_rate_date",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="gst_amount_base",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="import_batch",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="invoice_amount_base",
        ),
        migrations.RemoveField(
            model_name="servicefee",
            name="amount_base",
        ),
        migrations.RemoveField(
            model_name="servicefee",
            name="exchange_rate",
        ),
        migrations.RemoveField(
            model_name="servicefee",
            name="exchange_rate_date",
        ),
        migrations.RemoveField(
            model_name="servicefee",
            name="gst_amount",
        ),
        migrations.RemoveField(
            model_name="servicefee",
            name="gst_amount_base",
        ),
        migrations.AddField(
            model_name="airbooking",
            name="total_fare",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="advance_booking_days",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="policy_compliant",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="carhirebooking",
            name="country",
            field=models.CharField(default="Australia", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="carhirebooking",
            name="dropoff_city",
            field=models.CharField(default="Sydney", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="carhirebooking",
            name="vehicle_category",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="carhirebooking",
            name="vehicle_make_model",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="invoice",
            name="due_date",
            field=models.DateField(default="2025-10-27"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoice",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="servicefee",
            name="booking_channel",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="accommodationbooking",
            name="booking",
            field=models.ForeignKey(
                help_text="Parent booking - one booking can have multiple hotel stays",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accommodation_bookings",
                to="bookings.booking",
            ),
        ),
        migrations.AlterField(
            model_name="airbooking",
            name="booking",
            field=models.ForeignKey(
                help_text="Parent booking - one booking can have multiple air bookings",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="air_bookings",
                to="bookings.booking",
            ),
        ),
        migrations.AlterField(
            model_name="airbooking",
            name="primary_airline_iata_code",
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name="airbooking",
            name="primary_airline_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="airbooking",
            name="travel_class",
            field=models.CharField(
                choices=[
                    ("ECONOMY", "Economy"),
                    ("PREMIUM_ECONOMY", "Premium Economy"),
                    ("BUSINESS", "Business"),
                    ("FIRST", "First Class"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="airsegment",
            name="carbon_emissions_kg",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="agent_booking_reference",
            field=models.CharField(
                help_text="Master booking reference (e.g., GPT001)",
                max_length=100,
                verbose_name="Agent Booking Reference",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="exchange_rate",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="return_date",
            field=models.DateField(
                blank=True, help_text="End date of travel", null=True
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="supplier_reference",
            field=models.CharField(
                blank=True,
                help_text="Optional supplier confirmation number",
                max_length=100,
                verbose_name="Supplier Reference",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Total amount in original currency (sum of all air, hotel, car, fees)",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="travel_date",
            field=models.DateField(help_text="Start date of travel"),
        ),
        migrations.AlterField(
            model_name="carhirebooking",
            name="booking",
            field=models.ForeignKey(
                help_text="Parent booking - one booking can have multiple car rentals",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="car_hire_bookings",
                to="bookings.booking",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="bookings.booking",
            ),
        ),
        migrations.AlterField(
            model_name="servicefee",
            name="fee_type",
            field=models.CharField(
                choices=[
                    ("BOOKING_ONLINE_DOM", "Online Booking - Domestic"),
                    ("BOOKING_ONLINE_INTL", "Online Booking - International"),
                    ("BOOKING_OFFLINE_DOM", "Offline Booking - Domestic"),
                    ("BOOKING_OFFLINE_INTL", "Offline Booking - International"),
                    ("CHANGE_FEE", "Change Fee"),
                    ("REFUND_FEE", "Refund Fee"),
                    ("AFTER_HOURS", "After Hours Fee"),
                    ("CONSULTATION", "Consultation Fee"),
                    ("OTHER", "Other Fee"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="servicefee",
            name="import_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="service_fees",
                to="imports.importbatch",
            ),
        ),
        migrations.AddIndex(
            model_name="accommodationbooking",
            index=models.Index(
                fields=["booking"], name="accommodati_booking_f53d54_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="airbooking",
            index=models.Index(
                fields=["booking"], name="air_booking_booking_452436_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["status"], name="bookings_status_51373b_idx"),
        ),
        migrations.AddIndex(
            model_name="carhirebooking",
            index=models.Index(
                fields=["booking"], name="car_hire_bo_booking_1b90a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicefee",
            index=models.Index(
                fields=["booking"], name="service_fee_booking_e0586f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicefee",
            index=models.Index(
                fields=["fee_type"], name="service_fee_fee_typ_25a045_idx"
            ),
        ),
    ]
