# Generated by Django 5.2.7 on 2025-10-29 03:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0010_remove_booking_bookings_booking_a1dcd6_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="airbooking",
            name="base_fare",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="airbooking",
            name="currency",
            field=models.CharField(default="AUD", max_length=3),
        ),
        migrations.AddField(
            model_name="airbooking",
            name="fees",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="airbooking",
            name="taxes",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="airbooking",
            name="total_carbon_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total CO2 emissions in kg (sum of all segments)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="airbooking",
            name="potential_savings",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Amount that could have been saved if lowest fare was used",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="airbooking",
            name="primary_airline_iata_code",
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name="airbooking",
            name="primary_airline_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="airbooking",
            name="total_fare",
            field=models.DecimalField(decimal_places=2, default="0.00", max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="airbooking",
            name="travel_class",
            field=models.CharField(
                choices=[
                    ("FIRST", "First Class"),
                    ("BUSINESS", "Business Class"),
                    ("PREMIUM_ECONOMY", "Premium Economy"),
                    ("ECONOMY", "Economy"),
                    ("RESTRICTED_ECONOMY", "Restricted Economy"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="airsegment",
            name="carbon_emissions_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="CO2 emissions in kilograms for this segment (ICAO standards)",
                max_digits=8,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="carhirebooking",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
