# Generated by Django 5.2.7 on 2025-10-30 23:25

import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0012_bookingtransaction"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("TRANSACTION_CREATED", "Transaction Created"),
                            ("TRANSACTION_MODIFIED", "Transaction Modified"),
                            ("TRANSACTION_DELETED", "Transaction Deleted"),
                            ("BOOKING_CREATED", "Booking Created"),
                            ("BOOKING_MODIFIED", "Booking Modified"),
                            ("BOOKING_DELETED", "Booking Deleted"),
                            ("BOOKING_STATUS_CHANGED", "Booking Status Changed"),
                            ("COMPONENT_CREATED", "Component Created"),
                            ("COMPONENT_MODIFIED", "Component Modified"),
                            ("COMPONENT_DELETED", "Component Deleted"),
                            ("TOTAL_RECALCULATED", "Total Recalculated"),
                            ("CURRENCY_CONVERTED", "Currency Converted"),
                            ("REFUND_PROCESSED", "Refund Processed"),
                            ("NOTE_ADDED", "Note Added"),
                            ("SYSTEM_ACTION", "System Action"),
                        ],
                        db_index=True,
                        help_text="Type of action performed",
                        max_length=30,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this action occurred",
                    ),
                ),
                (
                    "object_id",
                    models.UUIDField(
                        blank=True,
                        help_text="ID of related object (if applicable)",
                        null=True,
                    ),
                ),
                (
                    "related_object_repr",
                    models.CharField(
                        blank=True,
                        help_text="String representation of related object (preserved even after deletion)",
                        max_length=255,
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of field that changed (if applicable)",
                        max_length=100,
                    ),
                ),
                (
                    "old_value",
                    models.JSONField(
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Previous value (JSON format)",
                        null=True,
                    ),
                ),
                (
                    "new_value",
                    models.JSONField(
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="New value (JSON format)",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Human-readable description of what changed"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes or context"
                    ),
                ),
                (
                    "user_repr",
                    models.CharField(
                        blank=True,
                        help_text="String representation of user (preserved even after user deletion)",
                        max_length=255,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address of user who made the change",
                        null=True,
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        help_text="The booking this audit log entry relates to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="bookings.booking",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="Type of related object (if applicable)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who performed this action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="booking_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking Audit Log",
                "verbose_name_plural": "Booking Audit Logs",
                "db_table": "booking_audit_logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["booking", "-timestamp"],
                        name="booking_aud_booking_dd8b41_idx",
                    ),
                    models.Index(
                        fields=["action", "-timestamp"],
                        name="booking_aud_action_604b6b_idx",
                    ),
                    models.Index(
                        fields=["user", "-timestamp"],
                        name="booking_aud_user_id_e0609d_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="booking_aud_content_3f489b_idx",
                    ),
                ],
            },
        ),
    ]
