# Generated by Django 5.2.7 on 2025-10-31 06:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0013_bookingauditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="accommodationbooking",
            name="gst_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="airbooking",
            name="gst_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="carhirebooking",
            name="gst_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="accommodationbooking",
            name="nightly_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="accommodationbooking",
            name="nightly_rate_base",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="accommodationbooking",
            name="total_amount_base",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="airbooking",
            name="base_fare",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="airbooking",
            name="lowest_fare_available",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="airbooking",
            name="potential_savings",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Amount that could have been saved if lowest fare was used",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="airbooking",
            name="taxes",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="airbooking",
            name="total_carbon_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total CO2 emissions in kg (sum of all segments)",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="airbooking",
            name="total_fare",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="airsegment",
            name="carbon_emissions_kg",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="CO2 emissions in kilograms for this segment (ICAO standards)",
                max_digits=8,
            ),
        ),
        migrations.AlterField(
            model_name="bookingtransaction",
            name="reason",
            field=models.CharField(
                blank=True,
                help_text="Reason for transaction (why was ticket exchanged, booking cancelled, etc.)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="carhirebooking",
            name="daily_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="carhirebooking",
            name="daily_rate_base",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="carhirebooking",
            name="total_amount_base",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
