# Generated by Django 5.2.7 on 2025-11-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0014_add_airbooking_financial_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total amount in original currency (auto-calculated from all components)",
                max_digits=10,
            ),
        ),
    ]
