# Generated by Django 5.2.8 on 2025-11-13 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0015_alter_booking_total_amount"),
        ("reference_data", "0005_hotel_hotelalias"),
    ]

    operations = [
        migrations.AddField(
            model_name="accommodationbooking",
            name="hotel",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to canonical hotel record (for master data management)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="reference_data.hotel",
            ),
        ),
        migrations.AlterField(
            model_name="accommodationbooking",
            name="hotel_name",
            field=models.CharField(
                help_text="Original hotel name from booking (preserved for history)",
                max_length=200,
            ),
        ),
        migrations.AddIndex(
            model_name="accommodationbooking",
            index=models.Index(fields=["hotel"], name="accommodati_hotel_i_d0a581_idx"),
        ),
    ]
