# Generated by Django 5.2.8 on 2025-11-17 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0016_accommodationbooking_hotel_servicefee_gst_amount_and_more"),
        ("organizations", "0004_organizationalnode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="servicefee",
            name="gst_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="GST Amount"
            ),
        ),
        migrations.AddField(
            model_name="servicefee",
            name="invoice_number",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Invoice Number"
            ),
        ),
        migrations.AddField(
            model_name="traveller",
            name="organizational_node",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to organizational hierarchy node (cost center, business unit, etc.)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="travellers",
                to="organizations.organizationalnode",
            ),
        ),
        migrations.AlterField(
            model_name="servicefee",
            name="fee_amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Fee Amount"
            ),
        ),
        migrations.AlterField(
            model_name="servicefee",
            name="fee_date",
            field=models.DateField(verbose_name="Invoice Date"),
        ),
        migrations.AlterField(
            model_name="traveller",
            name="cost_center",
            field=models.CharField(
                blank=True,
                help_text="DEPRECATED: Use organizational_node instead. Kept for backward compatibility.",
                max_length=100,
            ),
        ),
        migrations.AddIndex(
            model_name="traveller",
            index=models.Index(
                fields=["organizational_node"], name="travellers_organiz_e4c169_idx"
            ),
        ),
    ]
