# Generated by Django 4.2.7 on 2025-11-20 07:21

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0004_organizationalnode"),
        ("bookings", "0017_servicefee_gst_amount_servicefee_invoice_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreferredAirline",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "airline_iata_code",
                    models.CharField(
                        help_text="IATA airline code (e.g., QF for Qantas, SQ for Singapore Airlines)",
                        max_length=3,
                    ),
                ),
                (
                    "airline_name",
                    models.CharField(
                        help_text="Full airline name (e.g., Qantas Airways, Singapore Airlines)",
                        max_length=200,
                    ),
                ),
                (
                    "market_type",
                    models.CharField(
                        choices=[
                            ("DOMESTIC", "Domestic"),
                            ("INTERNATIONAL", "International"),
                        ],
                        db_index=True,
                        help_text="Whether this contract is for domestic or international travel",
                        max_length=20,
                    ),
                ),
                (
                    "markets_served",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of country codes served (e.g., ['UK', 'USA', 'SG']). For domestic, use ['ALL'] or leave empty.",
                    ),
                ),
                (
                    "routes_covered",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Specific routes covered (e.g., ['MEL-SYD', 'SYD-BNE']) or ['ALL'] for all routes",
                    ),
                ),
                (
                    "target_market_share",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Target market share percentage (e.g., 85.00 for 85%)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "target_revenue",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Target revenue amount in base currency (e.g., 500000.00 for $500,000)",
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "contract_start_date",
                    models.DateField(
                        db_index=True,
                        help_text="Date this airline contract becomes effective",
                    ),
                ),
                (
                    "contract_end_date",
                    models.DateField(
                        db_index=True, help_text="Date this airline contract expires"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this contract is currently active",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional contract details, terms, or special conditions",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this preferred airline record",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preferred_airlines_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Customer organization with this preferred airline contract",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferred_airlines",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Preferred Airline",
                "verbose_name_plural": "Preferred Airlines",
                "db_table": "preferred_airlines",
                "ordering": ["organization", "market_type", "airline_name"],
                "indexes": [
                    models.Index(
                        fields=["organization", "market_type"],
                        name="preferred_a_organiz_5346f4_idx",
                    ),
                    models.Index(
                        fields=["organization", "is_active"],
                        name="preferred_a_organiz_5a940a_idx",
                    ),
                    models.Index(
                        fields=["airline_iata_code"],
                        name="preferred_a_airline_da9d55_idx",
                    ),
                    models.Index(
                        fields=["contract_start_date", "contract_end_date"],
                        name="preferred_a_contrac_6c8f0b_idx",
                    ),
                ],
                "unique_together": {
                    (
                        "organization",
                        "airline_iata_code",
                        "market_type",
                        "contract_start_date",
                    )
                },
            },
        ),
    ]
