# Generated by Django 4.2.7 on 2025-11-20 07:45

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0018_preferredairline"),
    ]

    operations = [
        migrations.AddField(
            model_name='preferredairline',
            name='target_revenue',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Target revenue amount in base currency (e.g., 500000.00 for $500,000)",
                max_digits=12,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00"))
                ],
            ),
        ),
    ]
