# Generated by Django 4.2.7 on 2025-10-14 22:51

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Airline",
            fields=[
                (
                    "iata_code",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=200)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("alliance", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "db_table": "airlines",
                "ordering": ["iata_code"],
            },
        ),
        migrations.CreateModel(
            name="Airport",
            fields=[
                (
                    "iata_code",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("timezone", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "db_table": "airports",
                "ordering": ["iata_code"],
            },
        ),
        migrations.CreateModel(
            name="CurrencyExchangeRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("from_currency", models.CharField(max_length=3)),
                ("to_currency", models.CharField(max_length=3)),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.000001")
                            )
                        ],
                    ),
                ),
                ("rate_date", models.DateField()),
                ("rate_source", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "currency_exchange_rates",
                "ordering": ["-rate_date"],
                "indexes": [
                    models.Index(
                        fields=["from_currency", "to_currency", "rate_date"],
                        name="currency_ex_from_cu_cdedf2_idx",
                    ),
                    models.Index(
                        fields=["rate_date"], name="currency_ex_rate_da_1460ea_idx"
                    ),
                ],
                "unique_together": {("from_currency", "to_currency", "rate_date")},
            },
        ),
    ]
