# Generated by Django 4.2.7 on 2025-10-15 00:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("reference_data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarRentalCompany",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("alternative_names", models.JSONField(blank=True, default=list)),
                ("website", models.URLField(blank=True)),
                ("is_preferred", models.BooleanField(default=False)),
                (
                    "tier",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PREFERRED", "Preferred Supplier"),
                            ("APPROVED", "Approved Supplier"),
                            ("STANDARD", "Standard Supplier"),
                        ],
                        max_length=20,
                    ),
                ),
                ("has_corporate_rate", models.BooleanField(default=False)),
                (
                    "corporate_discount_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("account_manager_name", models.CharField(blank=True, max_length=200)),
                (
                    "account_manager_email",
                    models.EmailField(blank=True, max_length=254),
                ),
                ("account_manager_phone", models.CharField(blank=True, max_length=20)),
                ("contract_start_date", models.DateField(blank=True, null=True)),
                ("contract_end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Car Rental Companies",
                "db_table": "car_rental_companies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HotelChain",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("alternative_names", models.JSONField(blank=True, default=list)),
                ("website", models.URLField(blank=True)),
                ("is_preferred", models.BooleanField(default=False)),
                (
                    "tier",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PREFERRED", "Preferred Supplier"),
                            ("APPROVED", "Approved Supplier"),
                            ("STANDARD", "Standard Supplier"),
                        ],
                        max_length=20,
                    ),
                ),
                ("has_corporate_rate", models.BooleanField(default=False)),
                (
                    "corporate_discount_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("account_manager_name", models.CharField(blank=True, max_length=200)),
                (
                    "account_manager_email",
                    models.EmailField(blank=True, max_length=254),
                ),
                ("account_manager_phone", models.CharField(blank=True, max_length=20)),
                ("contract_start_date", models.DateField(blank=True, null=True)),
                ("contract_end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Hotel Chains",
                "db_table": "hotel_chains",
                "ordering": ["name"],
            },
        ),
    ]
