# Generated by Django 5.2.7 on 2025-10-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reference_data", "0002_carrentalcompany_hotelchain"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "alpha_2",
                    models.CharField(
                        help_text="ISO 3166-1 alpha-2 code (e.g., AU)",
                        max_length=2,
                        unique=True,
                    ),
                ),
                (
                    "alpha_3",
                    models.CharField(
                        help_text="ISO 3166-1 alpha-3 code (e.g., AUS)",
                        max_length=3,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "numeric_code",
                    models.CharField(
                        blank=True,
                        help_text="ISO 3166-1 numeric code (e.g., 036)",
                        max_length=3,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Official country name", max_length=100),
                ),
                (
                    "common_name",
                    models.CharField(
                        blank=True, help_text="Commonly used name", max_length=100
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        help_text="UN region: Africa, Americas, Asia, Europe, Oceania",
                        max_length=50,
                    ),
                ),
                (
                    "subregion",
                    models.CharField(
                        blank=True,
                        help_text="UN subregion: e.g., South-Eastern Asia, Western Europe",
                        max_length=50,
                    ),
                ),
                (
                    "currency_code",
                    models.CharField(
                        blank=True, help_text="ISO 4217 currency code", max_length=3
                    ),
                ),
                (
                    "phone_prefix",
                    models.CharField(
                        blank=True,
                        help_text="International dialing code",
                        max_length=10,
                    ),
                ),
                (
                    "is_domestic",
                    models.BooleanField(
                        default=False,
                        help_text="Is this the home country for this installation?",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Countries",
                "db_table": "countries",
                "ordering": ["name"],
            },
        ),
    ]
