# Generated by Django 5.2.7 on 2025-10-29 03:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reference_data", "0003_country"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="carrentalcompany",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="hotelchain",
            options={"ordering": ["name"]},
        ),
        migrations.RemoveField(
            model_name="country",
            name="is_domestic",
        ),
        migrations.AlterField(
            model_name="carrentalcompany",
            name="account_manager_phone",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="carrentalcompany",
            name="alternative_names",
            field=models.TextField(
                blank=True,
                help_text="Alternative names or abbreviations (comma-separated)",
            ),
        ),
        migrations.AlterField(
            model_name="carrentalcompany",
            name="corporate_discount_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Average discount percentage",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="carrentalcompany",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="carrentalcompany",
            name="tier",
            field=models.CharField(
                choices=[
                    ("PREFERRED", "Preferred Supplier"),
                    ("APPROVED", "Approved Supplier"),
                    ("STANDARD", "Standard Supplier"),
                ],
                default="STANDARD",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="alpha_2",
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="alpha_3",
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="country",
            name="common_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="country",
            name="currency_code",
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="country",
            name="numeric_code",
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name="country",
            name="phone_prefix",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="country",
            name="region",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="country",
            name="subregion",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="hotelchain",
            name="account_manager_phone",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hotelchain",
            name="alternative_names",
            field=models.TextField(
                blank=True,
                help_text="Alternative names or abbreviations (comma-separated)",
            ),
        ),
        migrations.AlterField(
            model_name="hotelchain",
            name="corporate_discount_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Average discount percentage off BAR (Best Available Rate)",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hotelchain",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="hotelchain",
            name="tier",
            field=models.CharField(
                choices=[
                    ("PREFERRED", "Preferred Supplier"),
                    ("APPROVED", "Approved Supplier"),
                    ("STANDARD", "Standard Supplier"),
                ],
                default="STANDARD",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="country",
            index=models.Index(fields=["region"], name="countries_region_b10b30_idx"),
        ),
        migrations.AddIndex(
            model_name="country",
            index=models.Index(
                fields=["subregion"], name="countries_subregi_c1bc75_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="country",
            index=models.Index(
                fields=["is_active"], name="countries_is_acti_f741bf_idx"
            ),
        ),
    ]
