# Generated by Django 5.2.8 on 2025-11-13 23:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference_data", "0004_alter_carrentalcompany_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "canonical_name",
                    models.CharField(
                        help_text="Current/official hotel name",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "hotel_chain",
                    models.CharField(
                        blank=True,
                        help_text="Hotel chain/brand (Marriott, Hilton, Accor, etc.)",
                        max_length=100,
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=100)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive if hotel closed or merged into another record",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes about merges, rebrands, or other relevant info",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "hotels",
                "ordering": ["canonical_name"],
                "indexes": [
                    models.Index(
                        fields=["canonical_name"], name="hotels_canonic_2cc2be_idx"
                    ),
                    models.Index(
                        fields=["hotel_chain"], name="hotels_hotel_c_77aa47_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="hotels_is_acti_af979d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HotelAlias",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "alias_name",
                    models.CharField(
                        help_text="Previous name, alternate spelling, or common abbreviation",
                        max_length=200,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Set to False to stop using this alias"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("REBRAND", "Hotel rebranded"),
                            ("ACQUISITION", "Acquired by another chain"),
                            ("TYPO", "Common misspelling or typo"),
                            ("ABBREVIATION", "Abbreviation or short name"),
                            ("OTHER", "Other reason"),
                        ],
                        default="OTHER",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hotel",
                    models.ForeignKey(
                        help_text="The canonical hotel this alias refers to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="reference_data.hotel",
                    ),
                ),
            ],
            options={
                "db_table": "hotel_aliases",
                "ordering": ["alias_name"],
                "indexes": [
                    models.Index(
                        fields=["hotel", "is_active"],
                        name="hotel_alias_hotel_i_f922a4_idx",
                    ),
                    models.Index(
                        fields=["alias_name"], name="hotel_alias_alias_n_642345_idx"
                    ),
                ],
                "unique_together": {("hotel", "alias_name")},
            },
        ),
    ]
