# Generated by Django 4.2.7 on 2025-10-16 20:49

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bookings", "0007_booking_travel_arranger_text_and_more"),
        ("imports", "0001_initial"),
        ("organizations", "0002_organization_ap_contact_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Commission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("AIR", "Air Travel"),
                            ("HOTEL", "Accommodation"),
                            ("CAR", "Car Hire"),
                            ("CRUISE", "Cruise"),
                            ("INSURANCE", "Travel Insurance"),
                            ("VISA", "Visa Services"),
                            ("TOUR", "Tours & Activities"),
                            ("RAIL", "Rail Travel"),
                            ("PACKAGE", "Package/Wholesale"),
                            ("OTHER", "Other Services"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "supplier_name",
                    models.CharField(
                        help_text="Airline, hotel chain, car rental company, etc.",
                        max_length=200,
                    ),
                ),
                (
                    "supplier_reference",
                    models.CharField(
                        blank=True,
                        help_text="Supplier's booking/confirmation reference for commission tracking",
                        max_length=100,
                    ),
                ),
                (
                    "commission_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Commission amount earned (from supplier)",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("currency", models.CharField(default="AUD", max_length=3)),
                (
                    "commission_amount_base",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Commission in organization's base currency",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=12, null=True
                    ),
                ),
                ("exchange_rate_date", models.DateField(blank=True, null=True)),
                (
                    "booking_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Booking amount (for commission % analysis)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "earned_date",
                    models.DateField(help_text="Date commission was earned"),
                ),
                (
                    "commission_period",
                    models.CharField(
                        blank=True,
                        help_text="Commission period, e.g., '2025-10' for October 2025",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commissions",
                        to="bookings.booking",
                    ),
                ),
                (
                    "import_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="commissions",
                        to="imports.importbatch",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Travel agent organization earning the commission",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commissions",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "commissions",
                "ordering": ["-earned_date"],
                "indexes": [
                    models.Index(
                        fields=["organization", "earned_date"],
                        name="commissions_organiz_e80c95_idx",
                    ),
                    models.Index(
                        fields=["booking"], name="commissions_booking_850959_idx"
                    ),
                    models.Index(
                        fields=["product_type", "supplier_name"],
                        name="commissions_product_a93461_idx",
                    ),
                    models.Index(
                        fields=["commission_period"],
                        name="commissions_commiss_a3ce50_idx",
                    ),
                ],
            },
        ),
    ]
