# Generated by Django 4.2.7 on 2025-10-16 05:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budgets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fiscalyear",
            name="fiscal_year_type",
            field=models.CharField(
                choices=[
                    ("AUS", "Australia (1 Jul - 30 Jun)"),
                    ("UK", "United Kingdom (1 Apr - 31 Mar)"),
                    ("USA", "United States (1 Jan - 31 Dec)"),
                    ("CALENDAR", "Calendar Year (1 Jan - 31 Dec)"),
                    ("CUSTOM", "Custom Period"),
                ],
                max_length=20,
            ),
        ),
    ]
