# Generated by Django 5.2.8 on 2025-11-17 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budgets", "0002_alter_fiscalyear_fiscal_year_type"),
        ("organizations", "0004_organizationalnode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="budget",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="budget",
            name="organizational_node",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to organizational hierarchy node (cost center, business unit, division, etc.)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budgets",
                to="organizations.organizationalnode",
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="cost_center",
            field=models.CharField(
                blank=True,
                help_text="DEPRECATED: Use organizational_node instead. Kept for backward compatibility.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="cost_center_name",
            field=models.CharField(
                blank=True,
                help_text="DEPRECATED: Use organizational_node.name instead. Kept for backward compatibility.",
                max_length=200,
            ),
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(
                fields=["organizational_node"], name="budgets_organiz_64c44d_idx"
            ),
        ),
    ]
