# Generated by Django 4.2.7 on 2025-10-14 03:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "org_type",
                    models.CharField(
                        choices=[
                            ("AGENT", "Travel Agent"),
                            ("CUSTOMER", "Customer Organization"),
                        ],
                        max_length=20,
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("contact_email", models.EmailField(max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                ("base_currency", models.CharField(default="AUD", max_length=3)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "travel_agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customers",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "organizations",
                "indexes": [
                    models.Index(fields=["code"], name="organizatio_code_c5d604_idx"),
                    models.Index(
                        fields=["org_type", "is_active"],
                        name="organizatio_org_typ_257757_idx",
                    ),
                ],
            },
        ),
    ]
