# Generated by Django 4.2.7 on 2025-10-16 00:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="ap_contact_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="AP Contact Email"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="ap_contact_name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="AP Contact Name"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="ap_contact_phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="AP Contact Phone"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="business_number",
            field=models.CharField(
                blank=True,
                help_text="ABN, ACN, or similar business registration number",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="contact_name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Contact Name"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="contact_position",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Contact Position"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="subscription_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="subscription_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="subscription_status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("TRIAL", "Trial Period"),
                    ("SUSPENDED", "Suspended"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
    ]
