# Generated by Django 5.2.7 on 2025-10-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0002_organization_ap_contact_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="home_country",
            field=models.CharField(
                default="AUS",
                help_text="ISO 3166-1 alpha-3 code for organization's home country (e.g., AUS, NZL, SGP)",
                max_length=3,
            ),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["home_country"], name="organizatio_home_co_1ea4a8_idx"
            ),
        ),
    ]
