# Generated by Django 5.2.8 on 2025-11-17 23:40

import django.db.models.deletion
import mptt.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_organization_home_country_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationalNode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Unique code for this node (e.g., 'VIC-001', 'Sales-ASPAC')",
                        max_length=100,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name for this node", max_length=200
                    ),
                ),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("COST_CENTER", "Cost Center"),
                            ("BUSINESS_UNIT", "Business Unit"),
                            ("REGION", "Region"),
                            ("DEPARTMENT", "Department"),
                            ("DIVISION", "Division"),
                            ("GROUP", "Group"),
                            ("OTHER", "Other"),
                        ],
                        default="COST_CENTER",
                        help_text="Type of organizational unit",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this node is currently active"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of this organizational unit",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization this node belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organizational_nodes",
                        to="organizations.organization",
                    ),
                ),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        help_text="Parent node in the hierarchy (null for root nodes)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="organizations.organizationalnode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organizational Node",
                "verbose_name_plural": "Organizational Nodes",
                "db_table": "organizational_nodes",
                "indexes": [
                    models.Index(
                        fields=["organization", "code"],
                        name="organizatio_organiz_6b29ba_idx",
                    ),
                    models.Index(
                        fields=["organization", "node_type"],
                        name="organizatio_organiz_0f618c_idx",
                    ),
                    models.Index(
                        fields=["organization", "is_active"],
                        name="organizatio_organiz_b76c4c_idx",
                    ),
                ],
                "unique_together": {("organization", "code")},
            },
        ),
    ]
