# Generated by Django 4.2.7 on 2025-10-14 23:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("import_date", models.DateField()),
                ("import_type", models.CharField(max_length=20)),
                ("file_name", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("PARTIAL", "Partially Completed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("records_processed", models.IntegerField(default=0)),
                ("records_created", models.IntegerField(default=0)),
                ("records_updated", models.IntegerField(default=0)),
                ("records_unchanged", models.IntegerField(default=0)),
                ("records_failed", models.IntegerField(default=0)),
                ("error_log", models.JSONField(blank=True, default=list)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_batches",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "import_batches",
                "ordering": ["-import_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "import_date"],
                        name="import_batc_organiz_2eb91b_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="import_batc_status_83cef5_idx",
                    ),
                ],
            },
        ),
    ]
